### ISSUE TITLE
Required to specify version for 'dspace-api' & 'dspace-services' dependencies.

### ISSUE THREAD

**Issue by engrjislam** [tdonohue/DSpace-Spring-Boot#3]
Build Failure if the version is not specified for 'dspace-api' & 'dspace-services' dependencies. I resolved this adding `<version>6.0</version>` to both dependencies like -- 

        
        <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-api</artifactId>
            <version>6.0</version>
            <exclusions>
                
                <exclusion>
                    <groupId>org.codehaus.woodstox</groupId>
                    <artifactId>wstx-asl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-services</artifactId>
            <version>6.0</version>
        </dependency>

**Comment by tdonohue** [comment]
This project is obsolete and no longer maintained. I'd recommend using https://github.com/DSpace/DSpace/  

See also the official DSpace Documentation at: https://wiki.duraspace.org/display/DSDOC
